# - workaround to keep docker-compose networking: https://stackoverflow.com/a/58391619
version: "3"
services:
  reservations-service:
    ports:
      - "8010:8010"
    image: "stoplight/prism:4.10.5"
    command:
      [
        "mock",
        "-h",
        "0.0.0.0",
        "-p",
        "8010",
        "/tmp/file.yaml"
      ]
    volumes:
      - "./reservations-service.yml:/tmp/file.yaml"
    platform: linux/amd64
