openapi: 3.0.3
info:
  description: |
    Restuarant Reservations Service REST API
  version: "v1"
  title: Reservations Service
paths:
  /health:
    get:
      summary: Health check
      description: Check the health of the service
      operationId: health_check
      responses:
        "200":
          description: Successful operation. Service is healthy.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - healthy
        "500":
          description: Internal server error
  /reservations:
    post:
      summary: Reserve table
      description: Reserve a table for a given time
      operationId: reserve_table
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TableReservationRequest"
      responses:
        "201":
          description: Successful operation. Reservation created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TableReservationResponse"
              examples:
                success:
                  summary: Reservation created
                  value:
                    reservationId: "reservation1"
                    restaurantId: "restaurant1"
                    startReservationTime: "2021-01-01T12:00:00Z"
                    endReservationTime: "2021-01-01T14:00:00Z"
                success2:
                  summary: Reservation created
                  value:
                    reservationId: "reservation2"
                    restaurantId: "restaurant2"
                    startReservationTime: "2021-01-01T18:00:00Z"
                    endReservationTime: null
        "400":
          description: Invalid input
        "409":
          description: Table not available
        "500":
          description: Internal server error

components:
  schemas:
    TableReservationRequest:
      type: object
      properties:
        restaurantId:
          type: string
        startReservationTime:
          type: string
          format: date-time
        endReservationTime:
          type: string
          format: date-time
        minimumSeats:
          type: integer
      required:
        - restaurantId
        - minimumSeats
        - startReservationTime
    TableReservationResponse:
      type: object
      properties:
        reservationId:
          type: string
        tableId:
          type: string
        startReservationTime:
          type: string
          format: date-time
        endReservationTime:
          type: string
          format: date-time
      required:
        - reservationId
        - tableId
        - startReservationTime
        - endReservationTime